# Firefox à travers VNC
# Mauvaise idée que de faire comme cela
# Mais c'est intéressant d'un point de vue didactique
# VERSION               1

FROM ubuntu

# Installation de vnc, xvfb dans le but d'afficher firefox
RUN apt update &&\
	apt install -y\
	firefox\
 	x11vnc\
	xvfb 

# Configuration/stockage du mot de passe
RUN mkdir ~/.vnc &&\
	x11vnc -storepasswd 1234 ~/.vnc/passwd

# On expose le port 5900 du conteneur (port par défaut de vnc)
EXPOSE 5900

# Commande réalisé au démarrage du conteneur (si pas surchargé)
CMD ["x11vnc", "-forever", "-usepw", "-create"]

# Instructions de compilations/exécutions:
# docker build . -t vnc
# docker run -it --rm -p 5900:5900 vnc
# On contacte le vlc du conteneur depuis l'hôte avec vncwiever localhost
