/* PROVENANCE d'un contenu (cours/article) — transparence éditoriale.
   Le contenu DÉCLARE un fait en frontmatter ; le rendu (pastille + barre de
   proportion) est DÉRIVÉ ici, défini UNE seule fois (DRY). Deux rôles :
   qui rédige (`by`) et qui relit/valide (`reviewedBy`) ; plus, le cas échéant,
   le modèle d'IA impliqué (`model`). Voir ProvBadge.astro et CLAUDE.md. */

export type ProvBy = "human" | "mixed" | "ai";
export type ProvReview = "none" | "human" | "ai";
/** Tuples typés pour z.enum (même forme que TOPIC_IDS / SERIE_IDS). */
export const PROV_BY = ["human", "mixed", "ai"] as [ProvBy, ...ProvBy[]];
export const PROV_REVIEW = ["none", "human", "ai"] as [ProvReview, ...ProvReview[]];

export interface Provenance {
  /** Qui a rédigé l'essentiel du contenu. */
  by: ProvBy;
  /** Qui a relu / validé (défaut : `none`). */
  reviewedBy?: ProvReview;
  /** Le(s) modèle(s) d'IA impliqué(s), en clair (ex. « Claude Opus 4.x »). */
  model?: string;
}

type Locale = "fr" | "en";
type Key = "human" | "human-ai" | "mixed" | "ai-human" | "ai-ai" | "ai";

export interface ProvView {
  /** Clé sémantique (CSS / data-attr). */
  key: Key;
  /** Icône Lucide (mappée dans Icon.astro). */
  icon: string;
  /** Part d'IA 0–100 — pilote la barre. ESTIMATION DÉCLARÉE, jamais une mesure. */
  ai: number;
  /** Cas « IA non relue par un humain » → badge fort de mise en garde. */
  warn: boolean;
  /** Libellé court de la pastille. */
  label: string;
  /** Phrase complète (infobulle). */
  title: string;
  /** Modèle, tel que déclaré. */
  model?: string;
}

function provKey(by: ProvBy, rev: ProvReview): Key {
  if (by === "human") return rev === "ai" ? "human-ai" : "human";
  if (by === "mixed") return "mixed";
  if (rev === "human") return "ai-human";
  if (rev === "ai") return "ai-ai";
  return "ai";
}

/** Part d'IA déclarée par niveau — règle la barre (humain ↔ IA), pas une mesure. */
const SHARE: Record<Key, number> = {
  human: 0, "human-ai": 15, mixed: 50, "ai-human": 85, "ai-ai": 92, ai: 100,
};

const ICON: Record<Key, string> = {
  human: "pen-line", "human-ai": "pen-line", mixed: "sparkles",
  "ai-human": "bot", "ai-ai": "bot", ai: "triangle-alert",
};

const LABEL: Record<Locale, Record<Key, string>> = {
  fr: {
    human: "Humain",
    "human-ai": "Humain · révisé IA",
    mixed: "Co-écrit humain + IA",
    "ai-human": "IA · révisé humain",
    "ai-ai": "IA · révisé IA",
    ai: "IA — non relu",
  },
  en: {
    human: "Human",
    "human-ai": "Human · AI-reviewed",
    mixed: "Human–AI co-written",
    "ai-human": "AI · human-reviewed",
    "ai-ai": "AI · AI-reviewed",
    ai: "AI — unreviewed",
  },
};

const TITLE: Record<Locale, Record<Key, string>> = {
  fr: {
    human: "Rédigé par un humain, sans IA.",
    "human-ai": "Rédigé par un humain, relu par une IA.",
    mixed: "Co-écrit par un humain et une IA.",
    "ai-human": "Rédigé par une IA, relu et validé par un humain.",
    "ai-ai": "Rédigé par une IA, relu par une IA — sans validation humaine.",
    ai: "Généré par une IA, sans relecture humaine — à lire avec prudence.",
  },
  en: {
    human: "Written by a human, no AI.",
    "human-ai": "Written by a human, reviewed by an AI.",
    mixed: "Co-written by a human and an AI.",
    "ai-human": "Written by an AI, reviewed and approved by a human.",
    "ai-ai": "Written by an AI, reviewed by an AI — no human sign-off.",
    ai: "Generated by an AI, with no human review — read with caution.",
  },
};

/** Vue d'affichage dérivée d'une provenance déclarée. */
export function provenanceView(p: Provenance, locale: Locale = "fr"): ProvView {
  const rev = p.reviewedBy ?? "none";
  const key = provKey(p.by, rev);
  // Mise en garde dès que l'humain n'a PAS relu un contenu rédigé par une IA.
  const warn = p.by === "ai" && rev !== "human";
  let title = TITLE[locale][key];
  if (p.model) title += locale === "fr" ? ` Modèle : ${p.model}.` : ` Model: ${p.model}.`;
  return {
    key,
    icon: warn ? "triangle-alert" : ICON[key],
    ai: SHARE[key],
    warn,
    label: LABEL[locale][key],
    title,
    model: p.model,
  };
}
