/* PROVENANCE d'un contenu (cours/article) — transparence éditoriale.
   Le contenu DÉCLARE un fait en frontmatter ; le rendu (pastille + barre de
   proportion) est DÉRIVÉ ici, défini UNE seule fois (DRY). Deux rôles :
   qui rédige (`by`) et qui relit/valide (`reviewedBy`) ; plus, le cas échéant,
   le modèle d'IA impliqué (`model`). Voir ProvBadge.astro et CLAUDE.md. */

export type ProvBy = "human" | "mixed" | "ai";
export type ProvReview = "none" | "human" | "ai";
/** Tuples typés pour z.enum (même forme que TOPIC_IDS / SERIE_IDS). */
export const PROV_BY = ["human", "mixed", "ai"] as [ProvBy, ...ProvBy[]];
export const PROV_REVIEW = ["none", "human", "ai"] as [ProvReview, ...ProvReview[]];

export interface Provenance {
  /** Qui a rédigé l'essentiel du contenu. */
  by: ProvBy;
  /** Qui a relu / validé (défaut : `none`). */
  reviewedBy?: ProvReview;
  /** Le(s) modèle(s) d'IA impliqué(s), en clair (ex. « Claude Opus 4.x »). */
  model?: string;
  /** Version traduite : qui a assuré la traduction. Orthogonal à `by`/`reviewedBy`
      (le fond reste celui de la langue d'origine ; seule la traduction change). */
  translated?: "human" | "ai";
  /** Part d'IA explicite (0–100). Optionnel : si fourni, il PRIME sur le défaut
      du niveau pour régler finement la barre. ESTIMATION DÉCLARÉE, pas une mesure. */
  aiShare?: number;
}

type Locale = "fr" | "en";
type Key = "human" | "human-ai" | "mixed" | "ai-human" | "ai-ai" | "ai";

export interface ProvView {
  /** Clé sémantique (CSS / data-attr). */
  key: Key;
  /** Icône Lucide (mappée dans Icon.astro). */
  icon: string;
  /** Part d'IA 0–100. ESTIMATION DÉCLARÉE, jamais une mesure. */
  ai: number;
  /** Part humaine 0–100 (= 100 − ai) — pilote la portion d'accent de la barre. */
  human: number;
  /** Cas « IA non relue par un humain » → badge fort de mise en garde. */
  warn: boolean;
  /** Libellé court de la pastille (mode compact / vignettes). */
  label: string;
  /** Phrase homogène (pastille en mode plein) : action + % éventuel + modèle. */
  desc: string;
  /** Phrase complète (infobulle). */
  title: string;
  /** Modèle, tel que déclaré. */
  model?: string;
  /** Suffixe de traduction (ex. « trad. IA »), si version traduite. */
  trans?: string;
  /** Pourcentage déclaré affiché (ex. « 25 % IA »), seulement si `aiShare` fourni. */
  shareText?: string;
}

function provKey(by: ProvBy, rev: ProvReview): Key {
  if (by === "human") return rev === "ai" ? "human-ai" : "human";
  if (by === "mixed") return "mixed";
  if (rev === "human") return "ai-human";
  if (rev === "ai") return "ai-ai";
  return "ai";
}

/** Part d'IA déclarée par niveau — règle la barre (humain ↔ IA), pas une mesure.
   La RELECTURE pèse peu sur la rédaction : « révisé IA » reste très humain,
   « révisé humain » reste très IA. */
const SHARE: Record<Key, number> = {
  human: 0, "human-ai": 10, mixed: 50, "ai-human": 90, "ai-ai": 95, ai: 100,
};

const ICON: Record<Key, string> = {
  human: "pen-line", "human-ai": "pen-line", mixed: "sparkles",
  "ai-human": "bot", "ai-ai": "bot", ai: "triangle-alert",
};

const LABEL: Record<Locale, Record<Key, string>> = {
  fr: {
    human: "Humain",
    "human-ai": "Humain · révisé IA",
    mixed: "Co-écrit humain + IA",
    "ai-human": "IA · révisé humain",
    "ai-ai": "IA · révisé IA",
    ai: "IA — non relu",
  },
  en: {
    human: "Human",
    "human-ai": "Human · AI-reviewed",
    mixed: "Human–AI co-written",
    "ai-human": "AI · human-reviewed",
    "ai-ai": "AI · AI-reviewed",
    ai: "AI — unreviewed",
  },
};

const TITLE: Record<Locale, Record<Key, string>> = {
  fr: {
    human: "Rédigé par un humain, sans IA.",
    "human-ai": "Rédigé par un humain, relu par une IA.",
    mixed: "Co-écrit par un humain et une IA.",
    "ai-human": "Rédigé par une IA, relu et validé par un humain.",
    "ai-ai": "Rédigé par une IA, relu par une IA — sans validation humaine.",
    ai: "Généré par une IA, sans relecture humaine — à lire avec prudence.",
  },
  en: {
    human: "Written by a human, no AI.",
    "human-ai": "Written by a human, reviewed by an AI.",
    mixed: "Co-written by a human and an AI.",
    "ai-human": "Written by an AI, reviewed and approved by a human.",
    "ai-ai": "Written by an AI, reviewed by an AI — no human sign-off.",
    ai: "Generated by an AI, with no human review — read with caution.",
  },
};

/** Suffixe « traduit par … » (orthogonal aux niveaux ci-dessus). */
const TRANS: Record<Locale, Record<"human" | "ai", string>> = {
  fr: { human: "trad. humaine", ai: "trad. IA" },
  en: { human: "human translation", ai: "AI-translated" },
};
const TRANS_TITLE: Record<Locale, Record<"human" | "ai", string>> = {
  fr: { human: " Traduction humaine.", ai: " Traduit par une IA." },
  en: { human: " Human translation.", ai: " AI-translated." },
};

/** Phrase homogène de la pastille (humain → IA), ex. « Révisé à 20 % par IA
   générative Claude Opus 4.x ». Le pourcentage n'apparaît QUE s'il est
   explicitement déclaré (`aiShare`) — sinon on évite la fausse précision. */
function buildDesc(
  key: Key, ai: number, model: string | undefined,
  declared: boolean, translated: "human" | "ai" | undefined, locale: Locale,
): string {
  if (locale === "fr") {
    const M = model ? `IA générative ${model}` : "une IA générative";
    const p = declared ? `à ${ai} % ` : "";
    let s: string;
    switch (key) {
      case "human": s = "Écrit par un humain"; break;
      case "human-ai": s = `Révisé ${p}par ${M}`; break;
      case "mixed": s = `Co-écrit ${p}par ${M}`; break;
      case "ai-human": s = `Rédigé ${p}par ${M}, relu par un humain`; break;
      case "ai-ai": s = `Rédigé ${p}par ${M}, relu par IA — sans validation humaine`; break;
      default: s = `Généré ${p}par ${M} — non relu`;
    }
    if (translated === "ai") s += " · trad. IA";
    else if (translated === "human") s += " · trad. humaine";
    return s;
  }
  const M = model ? `generative AI ${model}` : "a generative AI";
  const p = declared ? `${ai}% ` : "";
  let s: string;
  switch (key) {
    case "human": s = "Written by a human"; break;
    case "human-ai": s = `Reviewed ${p}by ${M}`; break;
    case "mixed": s = `Co-written ${p}by ${M}`; break;
    case "ai-human": s = `Written ${p}by ${M}, human-reviewed`; break;
    case "ai-ai": s = `Written ${p}by ${M}, AI-reviewed — no human sign-off`; break;
    default: s = `Generated ${p}by ${M} — unreviewed`;
  }
  if (translated === "ai") s += " · AI-translated";
  else if (translated === "human") s += " · human translation";
  return s;
}

/** Vue d'affichage dérivée d'une provenance déclarée. */
export function provenanceView(p: Provenance, locale: Locale = "fr"): ProvView {
  const rev = p.reviewedBy ?? "none";
  const key = provKey(p.by, rev);
  // Mise en garde dès que l'humain n'a PAS relu un contenu rédigé par une IA.
  const warn = p.by === "ai" && rev !== "human";
  // Pourcentage explicite éventuel : il PRIME sur le défaut du niveau pour la barre.
  const declared = typeof p.aiShare === "number";
  const ai = declared ? Math.max(0, Math.min(100, Math.round(p.aiShare as number))) : SHARE[key];
  let title = TITLE[locale][key];
  if (p.model) title += locale === "fr" ? ` Modèle : ${p.model}.` : ` Model: ${p.model}.`;
  if (p.translated) title += TRANS_TITLE[locale][p.translated];
  if (declared) title += locale === "fr" ? ` Part IA déclarée : ~${ai} %.` : ` Declared AI share: ~${ai}%.`;
  return {
    key,
    icon: warn ? "triangle-alert" : ICON[key],
    ai,
    human: 100 - ai,
    warn,
    label: LABEL[locale][key],
    desc: buildDesc(key, ai, p.model, declared, p.translated, locale),
    title,
    model: p.model,
    trans: p.translated ? TRANS[locale][p.translated] : undefined,
    shareText: declared ? (locale === "fr" ? `${ai} % IA` : `${ai}% AI`) : undefined,
  };
}
