#!/bin/bash
# Git lab replay — runs the course's 10-step exercise in a throwaway
# repository and asserts the expected states. The outputs shown in the
# course are generated by THIS script: what you read is what really
# happens. Fixed dates/identity make runs reproducible.
set -euo pipefail

dir="$(mktemp -d)"
trap 'rm -rf "$dir"' EXIT
cd "$dir"

export GIT_AUTHOR_NAME="ada" GIT_AUTHOR_EMAIL="ada@laptop"
export GIT_COMMITTER_NAME="ada" GIT_COMMITTER_EMAIL="ada@laptop"
export GIT_AUTHOR_DATE="2026-07-01T10:00:00 +0200"
export GIT_COMMITTER_DATE="2026-07-01T10:00:00 +0200"

step() { echo; echo "=== $* ==="; }

step "1. init"
mkdir mon_projet && cd mon_projet
git init -b main
[ -d .git ]

step "2. premier commit"
echo "<h1>Bienvenue sur mon site</h1>" > index.html
git add index.html
git status --short
git commit -m "Ajout de la page d'accueil"

step "3. second commit"
export GIT_AUTHOR_DATE="2026-07-01T10:05:00 +0200" GIT_COMMITTER_DATE="2026-07-01T10:05:00 +0200"
echo "<p>Ceci est un paragraphe.</p>" >> index.html
git add index.html
git commit -m "Ajout d'un paragraphe"

step "4. git log"
git log --oneline
[ "$(git log --oneline | wc -l)" -eq 2 ]

step "5. restaurer un fichier modifié"
echo "<p>une erreur" >> index.html
git restore index.html          # (git checkout -- index.html : forme historique)
if grep -q "erreur" index.html; then echo "restore failed"; exit 1; fi

step "6-7. revert du dernier commit"
export GIT_AUTHOR_DATE="2026-07-01T10:10:00 +0200" GIT_COMMITTER_DATE="2026-07-01T10:10:00 +0200"
git revert --no-edit HEAD
git log --oneline
[ "$(git log --oneline | wc -l)" -eq 3 ]        # le revert AJOUTE un commit
if grep -q "paragraphe" index.html; then echo "revert failed"; exit 1; fi

step "8-9. reset vers le premier commit"
first="$(git rev-list --max-parents=0 HEAD)"
git reset --hard "$first"
git log --oneline
[ "$(git log --oneline | wc -l)" -eq 1 ]        # le reset SUPPRIME les commits
cat index.html

echo
echo "OK — revert ajoute (historique conservé), reset supprime (historique réécrit)."
